"""
Pydantic schemas for the SatQuery Agentic Orchestration Layer.
"""

import datetime
import uuid
from typing import Any, Dict, List, Optional
from pydantic import BaseModel, Field


class AgentAnalyzeRequest(BaseModel):
    """Incoming request to the Agentic Query Router."""
    query: str = Field(..., min_length=1, max_length=2000, description="User natural-language query")
    image_ids: Optional[List[uuid.UUID]] = Field(default=None, description="List of satellite image identifiers")
    pair_id: Optional[uuid.UUID] = Field(default=None, description="Optional bi-temporal pair identifier")


class ConfidenceSchema(BaseModel):
    score: float = Field(..., ge=0.0, le=1.0, description="Calibrated confidence score [0.0 - 1.0]")
    method: str = Field(..., description="Method used for confidence calculation")


class ToolSummarySchema(BaseModel):
    name: str
    version: str
    task: str
    status: str
    description: Optional[str] = None


class TraceEventSchema(BaseModel):
    sequence: int
    event_type: str
    tool_name: Optional[str] = None
    status: str
    parameters: Optional[Dict[str, Any]] = None
    output_metadata: Optional[Dict[str, Any]] = None
    duration_ms: Optional[int] = None
    timestamp: datetime.datetime


class ExecutionTraceSchema(BaseModel):
    trace_id: uuid.UUID
    analysis_id: Optional[uuid.UUID] = None
    started_at: datetime.datetime
    completed_at: Optional[datetime.datetime] = None
    original_query: str
    normalized_query: str
    detected_task: str
    task_confidence: float
    input_image_ids: List[str]
    selected_tools: List[str]
    tool_parameters: Dict[str, Any] = Field(default_factory=dict)
    tool_status: str
    tool_outputs: Optional[Dict[str, Any]] = None
    errors: List[str] = Field(default_factory=list)
    total_duration_ms: int
    events: List[TraceEventSchema] = Field(default_factory=list)


class AgentAnalyzeResponse(BaseModel):
    """Contract returned by POST /api/v1/agent/analyze."""
    analysis_id: Optional[uuid.UUID] = None
    pair_id: Optional[uuid.UUID] = None
    status: str  # "completed", "unavailable", "ambiguous", "failed"
    task: str
    answer: str
    confidence: ConfidenceSchema
    tools: List[ToolSummarySchema] = Field(default_factory=list)
    evidence: List[Dict[str, Any]] = Field(default_factory=list)
    regions: List[Dict[str, Any]] = Field(default_factory=list)
    change_metrics: Optional[Dict[str, Any]] = None
    artifact_key: Optional[str] = None
    is_adapted: Optional[bool] = False
    adapter_id: Optional[str] = None
    fallback_used: Optional[bool] = False
    fallback_reason: Optional[str] = None
    trace_id: uuid.UUID
    trace: Optional[ExecutionTraceSchema] = None
    clarification_needed: Optional[str] = None
    observations: Optional[Dict[str, List[str]]] = None
    processing_time_ms: int


class PlanStepSchema(BaseModel):
    """A deterministic step within an executable Agent plan."""
    tool: str
    task: str
    parameters: Dict[str, Any] = Field(default_factory=dict)


class WorkflowPlanSchema(BaseModel):
    """Complete workflow plan generated by the WorkflowPlanner."""
    task: str
    steps: List[PlanStepSchema] = Field(default_factory=list)
    reasoning_summary: str
